version: '1.0'

services:
  busy_borg:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - common-network
  reservation:
    image: reservation:latest
    environment:
      - DATABASE_PORT=5432
      - DATABASE_IP=busy_borg
      - OAUTH2_PORT=8081
      - OAUTH2_URL=reverent_dhawan
    ports:
      - 8080:8080
    depends_on:
      - busy_borg
      - reverent_dhawan
    networks:
      - common-network
  reverent_dhawan:
    image: quay.io/keycloak/keycloak:24.0.3
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev", "--http-port=8081","--import-realm"]
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - 8081:8081
    networks:
      - common-network
networks:
  common-network:
    driver: bridge

